FROM nginx:latest

# Install OpenSSL
RUN apt-get update && apt-get install -y openssl

# Copy Nginx configuration
COPY ./nginx.conf /etc/nginx/nginx.conf

# Create SSL directory
RUN mkdir -p /etc/nginx/ssl

# Generate self-signed certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/CN=localhost"


# Expose HTTPS port
EXPOSE 443